INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (1, N'Overige', NULL)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (2, N'Mulitmedia', NULL)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (3, N'Bouw en doe het zelf', NULL)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (4, N'Bedrijfsinventaris', NULL)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (5, N'Auto''s en overig vervoer', NULL)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (6, N'Agrarisch', NULL)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (7, N'Audio en TV', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (8, N'Batterijen, accu''s en laders', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (9, N'Bekabeling', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (10, N'Computers', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (11, N'Foto en video', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (12, N'Hardware', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (13, N'Monitoren', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (14, N'Overige', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (15, N'Printers en kopieerapparaten', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (16, N'Professioneel AVL', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (17, N'Tablets', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (18, N'Telefonie', 2)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (19, N'Camera''s', 11)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (20, N'Fotostudio accesoires', 11)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (21, N'Standaarden', 11)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (22, N'Aggregaten, stroomkasten en kabels', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (23, N'Bebording en afzetmateriaal', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (24, N'Compressors', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (25, N'Gereedschap', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (26, N'Meetinstrumenten', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (27, N'Nat- en droogzuigers', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (28, N'Overige', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (29, N'Pompen', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (30, N'Trappen, ladders en steigers', 3)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (31, N'Haspels', 22)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (32, N'Omvormer', 22)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (33, N'Verlengkabel', 22)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (34, N'Hekken', 23)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (35, N'Elektrisch gereedschap', 25)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (36, N'Handgereedschap', 25)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (37, N'Pneumatisch gereedschap', 25)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (38, N'Lasers', 26)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (39, N'Temperatuurmeters', 26)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (40, N'Waterpassen', 26)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (41, N'Stofzuigers', 27)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (42, N'Beautysalon', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (43, N'Betaalsystemen', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (44, N'Beveiliging', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (45, N'BHV', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (46, N'Garage inventaris', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (47, N'Garderobe, Kantine', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (48, N'Horeca', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (49, N'Intern transport', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (50, N'Kantoor', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (51, N'Koffiemachines en drankautomaten', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (52, N'Magazijnkasten en stellingen', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (53, N'Overige', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (54, N'Reclamemateriaal', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (55, N'Reiniging', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (56, N'Vlaggenmasten en benodigdheden', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (57, N'Werkbanken', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (58, N'Werkplaatsinventaris', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (59, N'Winkel', 4)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (60, N'Apparatuur', 42)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (61, N'Massagetafels', 42)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (62, N'Kassa''s', 43)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (63, N'Sorteermachine', 43)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (64, N'Alarmsystemen', 44)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (65, N'Camera''s', 44)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (66, N'Brandblussers', 45)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (67, N'EHBO-dozen', 45)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (68, N'Apparatuur', 46)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (69, N'Bruggen', 46)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (70, N'Krikken', 46)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (71, N'Meters', 46)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (72, N'Opbergmogelijkheden', 46)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (73, N'Pompen', 46)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (74, N'2-kolomsbruggen', 69)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (75, N'4-kolomsbruggen', 69)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (76, N'Kapstokken', 47)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (77, N'Stoelen', 47)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (78, N'Tafels', 47)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (79, N'Machines', 48)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (80, N'Servies', 48)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (81, N'Bestek', 80)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (82, N'Borden', 80)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (83, N'Palletwagen', 49)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (84, N'Steekwagens', 49)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (85, N'Transportkarren', 49)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (86, N'Apparatuur', 50)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (87, N'Bureau''s', 50)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (88, N'Opbergmogelijkheden', 50)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (89, N'Stoelen', 50)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (90, N'Drankautomaten', 51)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (91, N'Koffiemachines', 51)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (92, N'Soepautomaten', 51)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (93, N'Kasten', 52)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (94, N'Rekken', 52)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (95, N'Stellingen', 52)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (96, N'Verrijdbaar', 94)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (97, N'Reclameborden', 54)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (98, N'Spandoekframe''s', 54)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (99, N'Ultrasoniche reinigers', 55)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (100, N'Veegmachines', 55)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (101, N'Aanhangwagens en accessoires', 5)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (102, N'Auto accessoires', 5)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (103, N'Auto onderdelen', 5)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (104, N'Bedrijfsauto''s', 5)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (105, N'overige', 5)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (106, N'Achteruitrijcamera''s', 102)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (107, N'Navigatiesystemen', 102)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (108, N'Verlichting', 102)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (109, N'Afrasteringsmateriaal', 6)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (110, N'Gewasbescherming en bemesting', 6)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (111, N'Oogstmachines', 6)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (112, N'Overige', 6)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (113, N'Parkmachines', 6)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (114, N'Tractoren en toebehoren', 6)
INSERT INTO [dbo].[Rubriek] ([rubrieknummer], [rubrieknaam], [parent]) VALUES (115, N'Veeteelt', 6)
